#!/bin/sh

## Move Markdown files and figures form the directory they are produced to the directory they must be in order to build the book.

## pwd must be "Documents/projects/programming-guide-for-the-capm-r-package"

# Clean directories

touch rmds/pt-br/tmp.html rmds/pt-br/tmp.png
rm rmds/pt-br/*.html
rm rmds/pt-br/*.png

# Move files
mv rmds/pt-br/*.md pt-br
