#!/bin/sh

## Move Markdown files and figures form the directory they are produced to the directory they must be in order to build the book.

## pwd must be "Documents/projects/programming-guide-for-the-capm-r-package"

# Clean directories

#rm rmds/en/*.html
#rm rmds/es/*.html
#rm rmds/pt-br/*.html

#rm rmds/en/*.png
#rm rmds/es/*.png
#rm rmds/pt-br/*.png

#rm en/*.md
#rm es/*.md
#rm pt-br/*.md

#rm en/figures/*
#rm es/figures/*
#rm pt-br/figures/*

# Move english files
mv rmds/en/*.md en
cp -a rmds/en/figures/. en/figures

# Move sapnish files
mv rmds/es/*.md es
cp -a rmds/es/figures/. es/figures

# Move portuguese files
mv rmds/pt-br/*.md pt-br
cp -a rmds/pt-br/figures/. pt-br/figures


