#!/bin/sh

## Move Markdown files and figures form the directory they are produced to the directory they must be in order to build the book.

## pwd must be "Documents/projects/programming-guide-for-the-capm-r-package"

# Clean directories

touch rmds/en/tmp.html rmds/en/tmp.png
rm rmds/en/*.html
rm rmds/en/*.png

# Move files
mv rmds/en/*.md en

