#!/bin/sh

## Move Markdown files and figures form the directory they are produced to the directory they must be in order to build the book.
## pwd must be "Documents/projects/programming-guide-for-the-capm-r-package"

# Move english *.md
mv rmds/en/*.md en

# Move english figures
cp -a rmds/en/figures/. en/figures


